#!/usr/bin/env perl

use strict;
use warnings;

use v5.014;

profile(@ARGV) unless caller;

sub profile {
    my (@args) = @_;

    foreach my $script_or_module (@args) {
        
        my $file = -e $script_or_module ? $script_or_module : undef;
        die "Invalid name: $script_or_module" if !$file && $script_or_module !~ qr{^[-:a-zA-z0-9_/\.]+$};

        if ( !$file ) {
            $file = qx{$^X -S perldoc -l $script_or_module}; # $^Xdoc :-)
            $? == 0 or die "Cannot find file for $script_or_module";
            chomp $file;
        }

        say qx[$^X -c -d:ProcessMemory $file 2>/dev/null];
    }

    return;
}

